### ISSUE TITLE
Investigate bug

### ISSUE THREAD

**Issue by danuker** [chevah/github-hooks-server#46]
Huh. Will have to investigate why @chevah-robot did not apply needs-changes .

_Originally posted by @danuker in https://github.com/chevah/server/issues/5939#issuecomment-1283900187_

**Comment by danuker** [comment]
The error was:

```
Traceback (most recent call last):
File "/home/site/wwwroot/chevah/github_hooks_server/server.py", line 81, in hook
response = handle_event(event)
File "/home/site/wwwroot/chevah/github_hooks_server/server.py", line 144, in handle_event
return handler.dispatch(event)
File "/home/site/wwwroot/chevah/github_hooks_server/handler.py", line 52, in dispatch
return handler(event)
File "/home/site/wwwroot/chevah/github_hooks_server/handler.py", line 115, in pull_request_review
remaining_reviewers = [
File "/home/site/wwwroot/chevah/github_hooks_server/handler.py", line 116, in <listcomp>
u.login
AttributeError: 'dict' object has no attribute 'login'
```

**Comment by danuker** [comment]
Fixed, but not yet deployed.
